name: Build branch

on:
  push:
    branches-ignore:
      - 1.*
      - main
    tags-ignore:
      - v1.*
      - v2.*

jobs:
  build-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.5', '2.6']

    steps:
    - uses: actions/checkout@v2
    - name: 💎 Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        # ruby-version: ${{ matrix.ruby-version }}
        ruby-version: 2.6.6
        bundler-cache: true
    - uses:  helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    # - name: 🧪 Run tests
    - run: gem install bundler:2.2.34
    - run: bundle _2.2.34_ add webrick
    - run: bundle install
    - run: bundle exec rake
